Repository HyperCube/HyperAPI, pull requests merged in 2018-08, with the labels that each got.

#11 [Codebuild]: Added build/deploy pipeline
  README.md
  buildspec.yml
  docs/generate_doc.sh
  requirements.txt
  scripts/deploy.py
Labels: ci/cd, enhancement

#18 Update Alerts and Reshapes routes with missing changes
  hdp_api/routes/alerts.py
  hdp_api/routes/datasetReshapes.py
Labels: bug

#19 Add missing report route
  hdp_api/routes/reports.py
Labels: bug

#22 Add route to access Dataset-level resources
  hdp_api/_router.py
  hdp_api/routes/datasetResources.py
Labels: enhancement
