Repository HyperCube/HyperAPI, pull requests merged in 2018-09, with the labels that each got.

#27 Add decorators to handle rerouting based on server versions
  hdp_api/_router.py
  hdp_api/routes/__init__.py
  hdp_api/routes/base/__init__.py
  hdp_api/routes/base/resource_base.py
  hdp_api/routes/base/route_base.py
  hdp_api/routes/base/validators.py
  hdp_api/routes/base/version_management.py
  utils/timeoutSettings.py
  utils/version.py
Labels: enhancement

#29 Fix and Update version management
  hdp_api/_router.py
  hdp_api/routes/base/resource_base.py
  hdp_api/routes/base/route_base.py
  hdp_api/routes/base/version_management.py
  sessionClass.py
Labels: fix

#30 Fix missing file
  hdp_api/routes/__init__.py
Labels: fix

#31 Update Version management to handle CI version
  utils/version.py
Labels: enhancement

#34 [CodeBuild]: Added docker image build pipeline
  buildspec.yml
  dist/Dockerfile
  requirements.txt
Labels: ci/cd
